global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['host.docker.internal:9113']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert_rules.yml"
